CREATE TABLE IF NOT EXISTS Customer (
    id SERIAL PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Book (
    id SERIAL PRIMARY KEY,
    title VARCHAR(20) NOT NULL UNIQUE,
    author VARCHAR(50) NOT NULL UNIQUE,
    genre VARCHAR(100) NOT NULL,
    isbn VARCHAR(100) NOT NULL,
    publisher VARCHAR(100) NOT NULL,
    year SMALLINT NOT NULL,
    quantity INTEGER NOT NULL,
    price MONEY NOT NULL
);